/** @type {import('tailwindcss').Config} */


const tailwindConfig = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/react-international-phone/**/*.{js,ts,jsx,tsx}",
  ],
  
  theme: {
    darkMode: "class",
    extend: {
      colors: {
        "success-light": "#3B6939",
        "success-light-on": "#FFFFFF",
        "success-light-container": "#BCF0B4",
        "success-light-on-container": "#002204",
        "success-dark": "#A1D39A",
        "success-dark-on": "#0A390F",
        "success-dark-container": "#235024",
        "success-dark-on-container": "#BCF0B4",
        "warning-light": "#775A0B",
        "warning-light-on": "#FFFFFF",
        "warning-light-container": "#FFDF9E",
        "warning-light-on-container": "#261A00",
        "warning-dark": "#E9C16C",
        "warning-dark-on": "#3F2E00",
        "warning-dark-container": "#5B4300",
        "warning-dark-on-container": "#FFDF9E",
        "info-light": "#36618E",
        "info-light-on": "#FFFFFF",
        "info-light-container": "#D1E4FF",
        "info-light-on-container": "#001D36",
        "info-dark": "#A0CAFD",
        "info-dark-on": "#003258",
        "info-dark-container": "#194975",
        "info-dark-on-container": "#D1E4FF",
        "attention-light": "#685F12",
        "attention-light-on": "#FFFFFF",
        "attention-light-container": "#F1E48A",
        "attention-light-on-container": "#201C00",
        "attention-dark": "#D4C871",
        "attention-dark-on": "#363100",
        "attention-dark-container": "#4F4800",
        "attention-dark-on-container": "#F1E48A",

        "light": {
          "primary": "#65558F",
          "surface-tint": "#65558F",
          "on-primary": "#FFFFFF",
          "primary-container": "#E9DDFF",
          "on-primary-container": "#4D3D75",
          "secondary": "#625B71",
          "on-secondary": "#FFFFFF",
          "secondary-container": "#E8DEF8",
          "on-secondary-container": "#4A4458",
          "tertiary": "#7E5260",
          "on-tertiary": "#FFFFFF",
          "tertiary-container": "#FFD9E3",
          "on-tertiary-container": "#633B48",
          "error": "#BA1A1A",
          "on-error": "#FFFFFF",
          "error-container": "#FFDAD6",
          "on-error-container": "#93000A",
          "background": "#FDF7FF",
          "on-background": "#1D1B20",
          "surface": "#FDF7FF",
          "on-surface": "#1D1B20",
          "surface-variant": "#E7E0EB",
          "on-surface-variant": "#49454E",
          "outline": "#7A757F",
          "outline-variant": "#CAC4CF",
          "shadow": "#000000",
          "scrim": "#000000",
          "inverse-surface": "#322F35",
          "inverse-on-surface": "#F5EFF7",
          "inverse-primary": "#CFBDFE",
          "primary-fixed": "#E9DDFF",
          "on-primary-fixed": "#201047",
          "primary-fixed-dim": "#CFBDFE",
          "on-primary-fixed-variant": "#4D3D75",
          "secondary-fixed": "#E8DEF8",
          "on-secondary-fixed": "#1E192B",
          "secondary-fixed-dim": "#CBC2DB",
          "on-secondary-fixed-variant": "#4A4458",
          "tertiary-fixed": "#FFD9E3",
          "on-tertiary-fixed": "#31101D",
          "tertiary-fixed-dim": "#EFB8C8",
          "on-tertiary-fixed-variant": "#633B48",
          "surface-dim": "#DED8E0",
          "surface-bright": "#FDF7FF",
          "surface-container-lowest": "#FFFFFF",
          "surface-container-low": "#F8F2FA",
          "surface-container": "#F2ECF4",
          "surface-container-high": "#ECE6EE",
          "surface-container-highest": "#E6E0E9",
        },
        "light-medium-contrast": {
          "primary": "#3C2D63",
          "surface-tint": "#65558F",
          "on-primary": "#FFFFFF",
          "primary-container": "#74649F",
          "on-primary-container": "#FFFFFF",
          "secondary": "#393347",
          "on-secondary": "#FFFFFF",
          "secondary-container": "#716A80",
          "on-secondary-container": "#FFFFFF",
          "tertiary": "#502B38",
          "on-tertiary": "#FFFFFF",
          "tertiary-container": "#8E606F",
          "on-tertiary-container": "#FFFFFF",
          "error": "#740006",
          "on-error": "#FFFFFF",
          "error-container": "#CF2C27",
          "on-error-container": "#FFFFFF",
          "background": "#FDF7FF",
          "on-background": "#1D1B20",
          "surface": "#FDF7FF",
          "on-surface": "#121016",
          "surface-variant": "#E7E0EB",
          "on-surface-variant": "#38353D",
          "outline": "#54515A",
          "outline-variant": "#6F6B75",
          "shadow": "#000000",
          "scrim": "#000000",
          "inverse-surface": "#322F35",
          "inverse-on-surface": "#F5EFF7",
          "inverse-primary": "#CFBDFE",
          "primary-fixed": "#74649F",
          "on-primary-fixed": "#FFFFFF",
          "primary-fixed-dim": "#5B4C84",
          "on-primary-fixed-variant": "#FFFFFF",
          "secondary-fixed": "#716A80",
          "on-secondary-fixed": "#FFFFFF",
          "secondary-fixed-dim": "#585267",
          "on-secondary-fixed-variant": "#FFFFFF",
          "tertiary-fixed": "#8E606F",
          "on-tertiary-fixed": "#FFFFFF",
          "tertiary-fixed-dim": "#734856",
          "on-tertiary-fixed-variant": "#FFFFFF",
          "surface-dim": "#CAC5CC",
          "surface-bright": "#FDF7FF",
          "surface-container-lowest": "#FFFFFF",
          "surface-container-low": "#F8F2FA",
          "surface-container": "#ECE6EE",
          "surface-container-high": "#E1DBE3",
          "surface-container-highest": "#D5D0D8",
        },

        "light-high-contrast": {
          "primary": "#312259",
          "surface-tint": "#65558F",
          "on-primary": "#FFFFFF",
          "primary-container": "#4F4078",
          "on-primary-container": "#FFFFFF",
          "secondary": "#2F293C",
          "on-secondary": "#FFFFFF",
          "secondary-container": "#4C465B",
          "on-secondary-container": "#FFFFFF",
          "tertiary": "#45212E",
          "on-tertiary": "#FFFFFF",
          "tertiary-container": "#663D4B",
          "on-tertiary-container": "#FFFFFF",
          "error": "#600004",
          "on-error": "#FFFFFF",
          "error-container": "#98000A",
          "on-error-container": "#FFFFFF",
          "background": "#FDF7FF",
          "on-background": "#1D1B20",
          "surface": "#FDF7FF",
          "on-surface": "#000000",
          "surface-variant": "#E7E0EB",
          "on-surface-variant": "#000000",
          "outline": "#2E2B33",
          "outline-variant": "#4B4851",
          "shadow": "#000000",
          "scrim": "#000000",
          "inverse-surface": "#322F35",
          "inverse-on-surface": "#FFFFFF",
          "inverse-primary": "#CFBDFE",
          "primary-fixed": "#4F4078",
          "on-primary-fixed": "#FFFFFF",
          "primary-fixed-dim": "#382960",
          "on-primary-fixed-variant": "#FFFFFF",
          "secondary-fixed": "#4C465B",
          "on-secondary-fixed": "#FFFFFF",
          "secondary-fixed-dim": "#353043",
          "on-secondary-fixed-variant": "#FFFFFF",
          "tertiary-fixed": "#663D4B",
          "on-tertiary-fixed": "#FFFFFF",
          "tertiary-fixed-dim": "#4C2734",
          "on-tertiary-fixed-variant": "#FFFFFF",
          "surface-dim": "#BCB7BF",
          "surface-bright": "#FDF7FF",
          "surface-container-lowest": "#FFFFFF",
          "surface-container-low": "#F5EFF7",
          "surface-container": "#E6E0E9",
          "surface-container-high": "#D8D2DA",
          "surface-container-highest": "#CAC5CC",
        },
        "dark": {
          "primary": "#CFBDFE",
          "surface-tint": "#CFBDFE",
          "on-primary": "#36275D",
          "primary-container": "#4D3D75",
          "on-primary-container": "#E9DDFF",
          "secondary": "#CBC2DB",
          "on-secondary": "#332D41",
          "secondary-container": "#4A4458",
          "on-secondary-container": "#E8DEF8",
          "tertiary": "#EFB8C8",
          "on-tertiary": "#4A2532",
          "tertiary-container": "#633B48",
          "on-tertiary-container": "#FFD9E3",
          "error": "#FFB4AB",
          "on-error": "#690005",
          "error-container": "#93000A",
          "on-error-container": "#FFDAD6",
          "background": "#141218",
          "on-background": "#E6E0E9",
          "surface": "#141218",
          "on-surface": "#E6E0E9",
          "surface-variant": "#49454E",
          "on-surface-variant": "#CAC4CF",
          "outline": "#948F99",
          "outline-variant": "#49454E",
          "shadow": "#000000",
          "scrim": "#000000",
          "inverse-surface": "#E6E0E9",
          "inverse-on-surface": "#322F35",
          "inverse-primary": "#65558F",
          "primary-fixed": "#E9DDFF",
          "on-primary-fixed": "#201047",
          "primary-fixed-dim": "#CFBDFE",
          "on-primary-fixed-variant": "#4D3D75",
          "secondary-fixed": "#E8DEF8",
          "on-secondary-fixed": "#1E192B",
          "secondary-fixed-dim": "#CBC2DB",
          "on-secondary-fixed-variant": "#4A4458",
          "tertiary-fixed": "#FFD9E3",
          "on-tertiary-fixed": "#31101D",
          "tertiary-fixed-dim": "#EFB8C8",
          "on-tertiary-fixed-variant": "#633B48",
          "surface-dim": "#141218",
          "surface-bright": "#3B383E",
          "surface-container-lowest": "#0F0D13",
          "surface-container-low": "#1D1B20",
          "surface-container": "#211F24",
          "surface-container-high": "#2B292F",
          "surface-container-highest": "#36343A",
        },

        "dark-medium-contrast": {
          "primary": "#E3D6FF",
          "surface-tint": "#CFBDFE",
          "on-primary": "#2B1B52",
          "primary-container": "#9887C5",
          "on-primary-container": "#000000",
          "secondary": "#E2D8F2",
          "on-secondary": "#282336",
          "secondary-container": "#958DA4",
          "on-secondary-container": "#000000",
          "tertiary": "#FFD0DD",
          "on-tertiary": "#3D1A27",
          "tertiary-container": "#B58392",
          "on-tertiary-container": "#000000",
          "error": "#FFD2CC",
          "on-error": "#540003",
          "error-container": "#FF5449",
          "on-error-container": "#000000",
          "background": "#141218",
          "on-background": "#E6E0E9",
          "surface": "#141218",
          "on-surface": "#FFFFFF",
          "surface-variant": "#49454E",
          "on-surface-variant": "#E0DAE5",
          "outline": "#B5B0BB",
          "outline-variant": "#938E99",
          "shadow": "#000000",
          "scrim": "#000000",
          "inverse-surface": "#E6E0E9",
          "inverse-on-surface": "#2B292F",
          "inverse-primary": "#4E3F77",
          "primary-fixed": "#E9DDFF",
          "on-primary-fixed": "#16033D",
          "primary-fixed-dim": "#CFBDFE",
          "on-primary-fixed-variant": "#3C2D63",
          "secondary-fixed": "#E8DEF8",
          "on-secondary-fixed": "#130E20",
          "secondary-fixed-dim": "#CBC2DB",
          "on-secondary-fixed-variant": "#393347",
          "tertiary-fixed": "#FFD9E3",
          "on-tertiary-fixed": "#240613",
          "tertiary-fixed-dim": "#EFB8C8",
          "on-tertiary-fixed-variant": "#502B38",
          "surface-dim": "#141218",
          "surface-bright": "#46434A",
          "surface-container-lowest": "#08070B",
          "surface-container-low": "#1F1D22",
          "surface-container": "#29272D",
          "surface-container-high": "#343138",
          "surface-container-highest": "#3F3C43",
        },
        "dark-high-contrast": {
          "primary": "#F5EDFF",
          "surface-tint": "#CFBDFE",
          "on-primary": "#000000",
          "primary-container": "#CBB9FA",
          "on-primary-container": "#0F0033",
          "secondary": "#F5EDFF",
          "on-secondary": "#000000",
          "secondary-container": "#C8BFD8",
          "on-secondary-container": "#0D081A",
          "tertiary": "#FFEBEF",
          "on-tertiary": "#000000",
          "tertiary-container": "#EBB4C4",
          "on-tertiary-container": "#1D020D",
          "error": "#FFECE9",
          "on-error": "#000000",
          "error-container": "#FFAEA4",
          "on-error-container": "#220001",
          "background": "#141218",
          "on-background": "#E6E0E9",
          "surface": "#141218",
          "on-surface": "#FFFFFF",
          "surface-variant": "#49454E",
          "on-surface-variant": "#FFFFFF",
          "outline": "#F4EEF9",
          "outline-variant": "#C6C0CB",
          "shadow": "#000000",
          "scrim": "#000000",
          "inverse-surface": "#E6E0E9",
          "inverse-on-surface": "#000000",
          "inverse-primary": "#4E3F77",
          "primary-fixed": "#E9DDFF",
          "on-primary-fixed": "#000000",
          "primary-fixed-dim": "#CFBDFE",
          "on-primary-fixed-variant": "#16033D",
          "secondary-fixed": "#E8DEF8",
          "on-secondary-fixed": "#000000",
          "secondary-fixed-dim": "#CBC2DB",
          "on-secondary-fixed-variant": "#130E20",
          "tertiary-fixed": "#FFD9E3",
          "on-tertiary-fixed": "#000000",
          "tertiary-fixed-dim": "#EFB8C8",
          "on-tertiary-fixed-variant": "#240613",
          "surface-dim": "#141218",
          "surface-bright": "#524F55",
          "surface-container-lowest": "#000000",
          "surface-container-low": "#211F24",
          "surface-container": "#322F35",
          "surface-container-high": "#3D3A41",
          "surface-container-highest": "#48464C",
        },
      },
      fontSize: {
        "display-large": ["57px", { lineHeight: "64px" }],
        "display-medium": ["45px", { lineHeight: "52px" }],
        "display-small": ["36px", { lineHeight: "44px" }],

        "headline-large": ["32px", { lineHeight: "40px" }],
        "headline-medium": ["28px", { lineHeight: "36px" }],
        "headline-small": ["24px", { lineHeight: "32px" }],

        "title-large": ["22px", { lineHeight: "28px" }],
        "title-medium": ["16px", { lineHeight: "24px" }],
        "title-small": ["14px", { lineHeight: "20px" }],

        "body-large": ["16px", { lineHeight: "24px" }],
        "body-medium": ["14px", { lineHeight: "20px" }],
        "body-small": ["12px", { lineHeight: "16px" }],

        "label-large": ["14px", { lineHeight: "20px" }],
        "label-medium": ["12px", { lineHeight: "16px" }],
        "label-small": ["11px", { lineHeight: "16px" }],
      },
      fontFamily: {
        roboto: ["Roboto", "serif"],
      },
      width: {
        "1/7": "14.2857%",
        "1/8": "12.5%",
        "1/9": "11.111%",
        "1/10": "10%",
      },
      screens: {
      'xxs': '600px', // very small screens
        sm: "600px",
        md: "840px",
        lg: "1200px",
        xl: "1600px",
      },
    },
  },
  plugins: [],
  palettes: {
    primary: {
      0: "#000000",
      5: "#160041",
      10: "#22005D",
      15: "#2D1067",
      20: "#381E72",
      25: "#432B7E",
      30: "#4F378A",
      35: "#5B4397",
      40: "#6750A4",
      50: "#8069BF",
      60: "#9A83DB",
      70: "#B69DF7",
      80: "#CFBCFF",
      90: "#E9DDFF",
      95: "#F6EEFF",
      98: "#FDF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    secondary: {
      0: "#000000",
      5: "#130E20",
      10: "#1E192B",
      15: "#282336",
      20: "#332D41",
      25: "#3E384C",
      30: "#4A4458",
      35: "#554F64",
      40: "#625B70",
      50: "#7B748A",
      60: "#958DA4",
      70: "#B0A7BF",
      80: "#CBC2DB",
      90: "#E8DEF8",
      95: "#F6EEFF",
      98: "#FDF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    tertiary: {
      0: "#000000",
      5: "#240612",
      10: "#31111D",
      15: "#3D1B27",
      20: "#4A2532",
      25: "#56303D",
      30: "#633B48",
      35: "#704654",
      40: "#7D5260",
      50: "#996A79",
      60: "#B58392",
      70: "#D29DAD",
      80: "#EFB8C8",
      90: "#FFD9E3",
      95: "#FFECF0",
      98: "#FFF8F8",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    neutral: {
      0: "#000000",
      5: "#121014",
      10: "#1C1B1E",
      15: "#272529",
      20: "#313033",
      25: "#3D3B3E",
      30: "#48464A",
      35: "#545156",
      40: "#605D62",
      50: "#79767A",
      60: "#938F94",
      70: "#AEAAAE",
      80: "#CAC5CA",
      90: "#E6E1E6",
      95: "#F4EFF4",
      98: "#FDF8FD",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
    "neutral-variant": {
      0: "#000000",
      5: "#121017",
      10: "#1D1A22",
      15: "#27242D",
      20: "#322F37",
      25: "#3D3A43",
      30: "#49454E",
      35: "#54515A",
      40: "#615D66",
      50: "#7A757F",
      60: "#948F99",
      70: "#AFA9B4",
      80: "#CAC4CF",
      90: "#E7E0EB",
      95: "#F5EEFA",
      98: "#FDF7FF",
      99: "#FFFBFF",
      100: "#FFFFFF",
    },
  },
};

const withMT = require("@material-tailwind/react/utils/withMT");

module.exports = withMT(tailwindConfig);

